media: "src/content/images"
content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
        required: true
      - name: image
        label: Image
        type: image
        required: true
      - name: imageAlt
        label: Image Alt Text
        type: string
        required: true
      
        